@startuml
hide circle
hide stereotype
hide members
hide methods
skinparam linetype ortho
skinparam class {
BackgroundColor<<LogicalModel>> #APPLICATION
BackgroundColor<<Profile>> #TECHNOLOGY
}
legend right
| <#APPLICATION>  Logical Model |
| <#TECHNOLOGY>  Profile |
endlegend
class "AdmissionEvaluation" <<LogicalModel>> [[StructureDefinition-AdmissionEvaluation.html]]
note top #PaleTurquoise [[ConceptMap-admissionEvaluation2FHIR-eu-hdr.html]]
Concept Map
endnote
class "composition-eu-hdr" <<Profile>> [[StructureDefinition-composition-eu-hdr.html]]
"AdmissionEvaluation" <|. "composition-eu-hdr"
@enduml