@startuml
hide circle
hide stereotype
hide members
hide methods
skinparam linetype ortho
skinparam class {
BackgroundColor<<LogicalModel>> #APPLICATION
BackgroundColor<<Profile>> #TECHNOLOGY
}
legend right
| <#APPLICATION>  Logical Model |
| <#TECHNOLOGY>  Profile |
endlegend
class "Alerts" <<LogicalModel>> [[StructureDefinition-Alerts.html]]
note top #PaleTurquoise [[ConceptMap-alerts2FHIR-eu-hdr.html]]
Concept Map
endnote
class "allergyIntolerance-eu-hdr" <<Profile>> [[StructureDefinition-allergyIntolerance-eu-hdr.html]]
"Alerts" <|. "allergyIntolerance-eu-hdr"
class "composition-eu-hdr" <<Profile>> [[StructureDefinition-composition-eu-hdr.html]]
"Alerts" <|. "composition-eu-hdr"
"allergyIntolerance-eu-hdr" -d[hidden]-> "composition-eu-hdr"
class "flag-eu-hdr" <<Profile>> [[StructureDefinition-flag-eu-hdr.html]]
"Alerts" <|. "flag-eu-hdr"
"composition-eu-hdr" -d[hidden]-> "flag-eu-hdr"
@enduml

