@startuml
hide circle
hide stereotype
hide members
hide methods
skinparam linetype ortho
skinparam class {
BackgroundColor<<LogicalModel>> #APPLICATION
BackgroundColor<<Profile>> #TECHNOLOGY
}
legend right
| <#APPLICATION>  Logical Model |
| <#TECHNOLOGY>  Profile |
endlegend
class "Alerts2FHIREuHdr" <<LogicalModel>> [[StructureDefinition-Alerts2FHIREuHdr.html]]
note top #PaleTurquoise [[ConceptMap-alerts2FHIR-eu-hdr.html]]
Concept Map
endnote
class "allergyIntolerance-eu-hdr" <<Profile>> [[StructureDefinition-allergyIntolerance-eu-hdr.html]]
"Alerts2FHIREuHdr" <|. "allergyIntolerance-eu-hdr"
class "composition-eu-hdr" <<Profile>> [[StructureDefinition-composition-eu-hdr.html]]
"Alerts2FHIREuHdr" <|. "composition-eu-hdr"
"allergyIntolerance-eu-hdr" -d[hidden]-> "composition-eu-hdr"
@enduml