@startuml
hide circle
hide stereotype
hide members
hide methods
skinparam linetype ortho
skinparam class {
BackgroundColor<<LogicalModel>> #APPLICATION
BackgroundColor<<Profile>> #TECHNOLOGY
}
legend right
| <#APPLICATION>  Logical Model |
| <#TECHNOLOGY>  Profile |
endlegend
class "Header" <<LogicalModel>> [[StructureDefinition-Header.html]]
note top #PaleTurquoise [[ConceptMap-hdrHeader2FHIR-eu-hdr.html]]
Concept Map
endnote
class "organization-eu" <<Profile>> [[https://hl7.eu/fhir/base/StructureDefinition-organization-eu.html]]
"Header" <|. "organization-eu"
class "patient-eu-core" <<Profile>> [[https://hl7.eu/fhir/base/StructureDefinition-patient-eu-core.html]]
"Header" <|. "patient-eu-core"
"organization-eu" -d[hidden]-> "patient-eu-core"
class "practitionerRole-eu-core" <<Profile>> [[https://hl7.eu/fhir/base/StructureDefinition-practitionerRole-eu-core.html]]
"Header" <|. "practitionerRole-eu-core"
"patient-eu-core" -d[hidden]-> "practitionerRole-eu-core"
class "bundle-eu-hdr" <<Profile>> [[StructureDefinition-bundle-eu-hdr.html]]
"Header" <|. "bundle-eu-hdr"
"practitionerRole-eu-core" -d[hidden]-> "bundle-eu-hdr"
class "composition-eu-hdr" <<Profile>> [[StructureDefinition-composition-eu-hdr.html]]
"Header" <|. "composition-eu-hdr"
"bundle-eu-hdr" -d[hidden]-> "composition-eu-hdr"
class "Coverage" <<Profile>> [[http://hl7.org/fhir/StructureDefinition/Coverage]]
"Header" <|. "Coverage"
"composition-eu-hdr" -d[hidden]-> "Coverage"
class "ServiceRequest" <<Profile>> [[http://hl7.org/fhir/StructureDefinition/ServiceRequest]]
"Header" <|. "ServiceRequest"
"Coverage" -d[hidden]-> "ServiceRequest"
@enduml
