@startuml
skinparam class {
    BackgroundColor<<LogicalModel>> #FFCC00
    BackgroundColor<<Profile>> #CCCCFF
}
skinparam linetype ortho
legend right
  | <#FFCC00> | Logical Model |
  | <#CCCCFF> | Profile |
endlegend
class "HospitalDischargeReport" <<LogicalModel>> [[StructureDefinition-HospitalDischargeReport.html]]
note right #PaleTurquoise [[ConceptMap-HeaderMeta2FHIR-eu-hdr.html]]
Concept Map
endnote
class "bundle-eu-hdr" <<Profile>> [[StructureDefinition-bundle-eu-hdr.html]]
"HospitalDischargeReport" --> "bundle-eu-hdr"
class "composition-eu-hdr" <<Profile>> [[StructureDefinition-composition-eu-hdr.html]]
"HospitalDischargeReport" --> "composition-eu-hdr"
"bundle-eu-hdr" -[hidden]-> "composition-eu-hdr"
class "composition-eu-hdr" <<Profile>> [[StructureDefinition-composition-eu-hdr.html]]
"HospitalDischargeReport" --> "composition-eu-hdr"
"composition-eu-hdr" -[hidden]-> "composition-eu-hdr"
@enduml