@startuml
hide circle
hide stereotype
hide members
hide methods
skinparam linetype ortho
skinparam class {
BackgroundColor<<LogicalModel>> #APPLICATION
BackgroundColor<<Profile>> #TECHNOLOGY
}
legend right
| <#APPLICATION>  Logical Model |
| <#TECHNOLOGY>  Profile |
endlegend
class "InPatientEncounter" <<LogicalModel>> [[StructureDefinition-InPatientEncounter.html]]
note top #PaleTurquoise [[ConceptMap-encounter2FHIR-eu-hdr.html]]
Concept Map
endnote
class "encounter-eu-hdr" <<Profile>> [[StructureDefinition-encounter-eu-hdr.html]]
"InPatientEncounter" <|. "encounter-eu-hdr"
class "location-eu-hdr" <<Profile>> [[StructureDefinition-location-eu-hdr.html]]
"InPatientEncounter" <|. "location-eu-hdr"
"encounter-eu-hdr" -d[hidden]-> "location-eu-hdr"
class "organization-eu-hdr" <<Profile>> [[StructureDefinition-organization-eu-hdr.html]]
"InPatientEncounter" <|. "organization-eu-hdr"
"location-eu-hdr" -d[hidden]-> "organization-eu-hdr"
class "practitioner-eu-hdr" <<Profile>> [[StructureDefinition-practitioner-eu-hdr.html]]
"InPatientEncounter" <|. "practitioner-eu-hdr"
"organization-eu-hdr" -d[hidden]-> "practitioner-eu-hdr"
class "practitionerRole-eu-hdr" <<Profile>> [[StructureDefinition-practitionerRole-eu-hdr.html]]
"InPatientEncounter" <|. "practitionerRole-eu-hdr"
"practitioner-eu-hdr" -d[hidden]-> "practitionerRole-eu-hdr"
@enduml