@startuml
hide circle
hide stereotype
hide members
hide methods
skinparam linetype ortho
skinparam class {
BackgroundColor<<LogicalModel>> #APPLICATION
BackgroundColor<<Profile>> #TECHNOLOGY
}
legend right
| <#APPLICATION>  Logical Model |
| <#TECHNOLOGY>  Profile |
endlegend
class "Recommendations" <<LogicalModel>> [[StructureDefinition-Recommendations.html]]
note top #PaleTurquoise [[ConceptMap-recommendations2FHIR-eu-hdr.html]]
Concept Map
endnote
class "composition-eu-hdr" <<Profile>> [[StructureDefinition-composition-eu-hdr.html]]
"Recommendations" <|. "composition-eu-hdr"
@enduml