@startuml
hide circle
hide stereotype
hide members
hide methods
skinparam linetype ortho
skinparam class {
BackgroundColor<<LogicalModel>> #APPLICATION
BackgroundColor<<Profile>> #TECHNOLOGY
}
legend right
| <#APPLICATION>  Logical Model |
| <#TECHNOLOGY>  Profile |
endlegend
class "Subject" <<LogicalModel>> [[StructureDefinition-Subject.html]]
note top #PaleTurquoise [[ConceptMap-subject2FHIR-eu-hdr.html]]
Concept Map
endnote
class "patient-eu-hdr" <<Profile>> [[StructureDefinition-patient-eu-hdr.html]]
"Subject" <|. "patient-eu-hdr"
class "practitioner-eu-hdr" <<Profile>> [[StructureDefinition-practitioner-eu-hdr.html]]
"Subject" <|. "practitioner-eu-hdr"
"patient-eu-hdr" -d[hidden]-> "practitioner-eu-hdr"
class "practitionerRole-eu-hdr" <<Profile>> [[StructureDefinition-practitionerRole-eu-hdr.html]]
"Subject" <|. "practitionerRole-eu-hdr"
"practitioner-eu-hdr" -d[hidden]-> "practitionerRole-eu-hdr"
@enduml