@startmindmap
* body
** Presented form
** Advance directives
** Alerts
** Encounter
** Admission evaluation
** Hx general Reported
** Course of hospitalisation
** Discharge details
** Care plan and other recommendations after discharge.
@endmindmap