@startuml
hide circle
hide stereotype
hide members
hide methods
skinparam linetype ortho
skinparam class {
BackgroundColor<<LogicalModel>> #APPLICATION
BackgroundColor<<Profile>> #TECHNOLOGY
}
legend right
| <#APPLICATION>  Logical Model |
| <#TECHNOLOGY>  Profile |
endlegend
class "PlanOfCare" <<LogicalModel>> [[StructureDefinition-PlanOfCare.html]]
note top #PaleTurquoise [[ConceptMap-planOfCare2FHIR-eu-hdr.html]]
Concept Map
endnote
class "carePlan-eu-hdr" <<Profile>> [[StructureDefinition-carePlan-eu-hdr.html]]
"PlanOfCare" <|. "carePlan-eu-hdr"
@enduml